steps:
  - label: ':pipeline: Pipeline upload example2'
    command: echo "Hello Buildkite!"

  -label: ":thinking_face: Check the env var exists"
  command: "./check_environment_var.sh"

  - wait:

  # This example references GIT_SHORT_HASH directly, so should be escaped 
  # so the agent executing the job fetches from its own environment
  - label: ":white_check_mark: Use the env var somewhere else!"
    command: "buildkite-agent annotate \"**The evaluated environment variable was:** GIT_SHORT_HASH=$$GIT_SHORT_HASH :tada:\""

  - name: ':pipeline: check test file'
    command: "/VishalKrishiSevaKendra/custom-fold/test.rb"

  - name: ':pipeline: aws secret managers'
    commands: echo $SECRET_FROM_OTHER_ACCOUNT
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            SECRET_FROM_OTHER_ACCOUNT: "arn:aws:secretsmanager:us-east-2:212711382622:secret:TestSecret"
          file:
            - path: "save-my-other-secret-here"
              secret-id: "arn:aws:secretsmanager:us-east-2:212711382622:secret:TestSecret"