steps:
  - label: ':pipeline: Pipeline upload example'
    command: echo "Hello Buildkite!"

  - name: ':pipeline: aws secret managers'
    commands: 'echo \$SECRET_FROM_OTHER_REGION'
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          region: us-east-2
          env:
            SECRET_FROM_OTHER_REGION: TestSecret