 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/casts", type: :request do
  
  # Cast. As you add validations to Cast, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cast.create! valid_attributes
      get casts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cast = Cast.create! valid_attributes
      get cast_url(cast)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cast_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      cast = Cast.create! valid_attributes
      get edit_cast_url(cast)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cast" do
        expect {
          post casts_url, params: { cast: valid_attributes }
        }.to change(Cast, :count).by(1)
      end

      it "redirects to the created cast" do
        post casts_url, params: { cast: valid_attributes }
        expect(response).to redirect_to(cast_url(Cast.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cast" do
        expect {
          post casts_url, params: { cast: invalid_attributes }
        }.to change(Cast, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post casts_url, params: { cast: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cast" do
        cast = Cast.create! valid_attributes
        patch cast_url(cast), params: { cast: new_attributes }
        cast.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cast" do
        cast = Cast.create! valid_attributes
        patch cast_url(cast), params: { cast: new_attributes }
        cast.reload
        expect(response).to redirect_to(cast_url(cast))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        cast = Cast.create! valid_attributes
        patch cast_url(cast), params: { cast: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cast" do
      cast = Cast.create! valid_attributes
      expect {
        delete cast_url(cast)
      }.to change(Cast, :count).by(-1)
    end

    it "redirects to the casts list" do
      cast = Cast.create! valid_attributes
      delete cast_url(cast)
      expect(response).to redirect_to(casts_url)
    end
  end
end
